name:                nw-alignment
version:             0.1.0.0
author:              "Phillip Le, Emily Lo"
maintainer:          "N/A"

# extra-source-files:

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
# description:

dependencies:
- base >= 4.7 && < 5
- parallel
- array

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
  ghc-options:
    - -eventlog

executables:
  nw-alignment:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -O2
    dependencies:
    - nw-alignment


tests:
  nw-aligner-test:
    main:               Spec.hs
    source-dirs:        test
    ghc-options:
    - -threaded
    - -rtsopts
    dependencies:
    - HUnit

